# Generated by Django 3.2.9 on 2022-01-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bg',
            field=models.ImageField(default=1, upload_to='user-bg/', verbose_name='Задний фон'),
            preserve_default=False,
        ),
    ]
