# Generated by Django 3.2.9 on 2022-04-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=140, verbose_name='Имя')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
        ),
    ]
