# Generated by Django 3.2.9 on 2022-01-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom',
            name='bg',
        ),
        migrations.AddField(
            model_name='custom',
            name='castom_bg',
            field=models.ImageField(blank=True, null=True, upload_to='custom/'),
        ),
    ]
