# Generated by Django 3.2.9 on 2022-01-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
